---
name: instagram_clone
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.2
  uuid: ^4.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assests/ic_instagram.svg
